name: 'Agent Trust Scan'
description: 'Validate agent/tool endpoints across A2A, MCP, and llms.txt protocols'
author: 'Agent Trust'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  domains:
    description: 'Comma-separated list of domains to scan, or path to file with domains'
    required: true
  fail-on:
    description: 'Fail the action on: warn|fail (default: fail)'
    required: false
    default: 'fail'
  format:
    description: 'Output format: table|json|markdown (default: markdown)'
    required: false
    default: 'markdown'
  post-comment:
    description: 'Post results as PR comment (requires github-token)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for posting PR comments (use ${{ secrets.GITHUB_TOKEN }})'
    required: false

outputs:
  score:
    description: 'Overall scan score (0-100)'
    value: ${{ steps.scan.outputs.score }}
  passed:
    description: 'Whether all checks passed'
    value: ${{ steps.scan.outputs.passed }}
  report:
    description: 'Full scan report (JSON)'
    value: ${{ steps.scan.outputs.report }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Build agent-trust-scan
      shell: bash
      run: |
        # Use the local checkout instead of installing from npm
        cd $GITHUB_ACTION_PATH
        npm ci
        npm run build
    
    - name: Run scan
      id: scan
      shell: bash
      env:
        DOMAINS: ${{ inputs.domains }}
        FORMAT: ${{ inputs.format }}
        FAIL_ON: ${{ inputs.fail-on }}
        POST_COMMENT: ${{ inputs.post-comment }}
      run: |
        # Use local build instead of global install
        SCAN_BIN="node $GITHUB_ACTION_PATH/dist/cli.js"
        
        # Determine if domains is a file or comma-separated list
        if [ -f "$DOMAINS" ]; then
          DOMAINS_ARG="--domains $DOMAINS"
        else
          # Convert comma-separated to newline-separated
          DOMAINS_FILE=$(mktemp)
          echo "$DOMAINS" | tr ',' '\n' > "$DOMAINS_FILE"
          DOMAINS_ARG="--domains $DOMAINS_FILE"
        fi
        
        # Run scan with user's requested format for console output
        echo "Running scan with format: $FORMAT"
        set +e
        $SCAN_BIN $DOMAINS_ARG --format "$FORMAT"
        SCAN_EXIT_CODE=$?
        set -e
        
        # Also capture JSON for machine parsing
        $SCAN_BIN $DOMAINS_ARG --format json > scan-report.json
        
        # Parse JSON using Node.js (no jq dependency)
        cat > parse-report.js << 'PARSER_EOF'
        const fs = require('fs');
        const data = JSON.parse(fs.readFileSync('scan-report.json', 'utf8'));
        
        // Handle both single domain and array of domains
        const reports = Array.isArray(data) ? data : [data];
        
        // Compute minimum score across all domains (best for gating)
        const minScore = Math.min(...reports.map(r => r.score));
        console.log(`SCORE=${minScore}`);
        
        // Count failures and warnings across all domains
        let totalFails = 0;
        let totalWarns = 0;
        
        for (const report of reports) {
          const checks = Object.values(report.checks);
          totalFails += checks.filter(c => c.status === 'fail').length;
          totalWarns += checks.filter(c => c.status === 'warn').length;
        }
        
        console.log(`FAIL_COUNT=${totalFails}`);
        console.log(`WARN_COUNT=${totalWarns}`);
        PARSER_EOF
        
        # Run parser and capture output
        PARSE_OUTPUT=$(node parse-report.js)
        
        # Extract values
        SCORE=$(echo "$PARSE_OUTPUT" | grep "^SCORE=" | cut -d= -f2)
        FAIL_COUNT=$(echo "$PARSE_OUTPUT" | grep "^FAIL_COUNT=" | cut -d= -f2)
        WARN_COUNT=$(echo "$PARSE_OUTPUT" | grep "^WARN_COUNT=" | cut -d= -f2)
        
        echo "score=$SCORE" >> $GITHUB_OUTPUT
        
        # Save full JSON report
        echo "report<<EOF" >> $GITHUB_OUTPUT
        cat scan-report.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        # Generate markdown report for PR comments
        if [ "$POST_COMMENT" = "true" ]; then
          $SCAN_BIN $DOMAINS_ARG --format markdown > scan-report.md
        fi
        
        # Determine pass/fail
        if [ "$FAIL_ON" = "warn" ] && [ "$WARN_COUNT" -gt 0 ]; then
          echo "passed=false" >> $GITHUB_OUTPUT
          exit 1
        elif [ "$FAIL_COUNT" -gt 0 ]; then
          echo "passed=false" >> $GITHUB_OUTPUT
          exit 1
        else
          echo "passed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Post PR comment
      if: always() && inputs.post-comment == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('scan-report.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🔍 Agent Trust Scan Results\n\n${report}`
          });
